-- Kwartje — seed: system merchants.
-- Spec: docs/02-market-nl.md §6 (merchant list, split by descriptor family;
-- every "A/B" pairing in that doc is seeded as two separate merchants).
-- default_category_id is looked up by category key (01_categories.sql must
-- run first). Fintech/P2P rails (Tikkie, iDEAL, PayPal, …) get no default
-- category: they wrap an underlying real merchant and are handled by the
-- descriptor-heuristics stage (docs/09 §1 stage 6), not a merchant default.
-- Idempotent: targets the partial unique index on (key) where
-- household_id is null (see 09_supporting.sql migration).

insert into merchants (household_id, key, display_name, default_category_id, match_patterns, is_system) values
-- Boodschappen
(null, 'albert_heijn', 'Albert Heijn', (select id from categories where key = 'boodschappen' and household_id is null), array['albert heijn'], true),
(null, 'ah_to_go', 'AH to go', (select id from categories where key = 'boodschappen' and household_id is null), array['ah to go'], true),
(null, 'jumbo', 'Jumbo', (select id from categories where key = 'boodschappen' and household_id is null), array['jumbo'], true),
(null, 'lidl', 'Lidl', (select id from categories where key = 'boodschappen' and household_id is null), array['lidl'], true),
(null, 'aldi', 'Aldi', (select id from categories where key = 'boodschappen' and household_id is null), array['aldi'], true),
(null, 'plus', 'Plus', (select id from categories where key = 'boodschappen' and household_id is null), array['plus supermarkt'], true),
(null, 'dirk', 'Dirk', (select id from categories where key = 'boodschappen' and household_id is null), array['dirk van den broek', 'dirk'], true),
(null, 'coop', 'Coop', (select id from categories where key = 'boodschappen' and household_id is null), array['coop'], true),
(null, 'spar', 'Spar', (select id from categories where key = 'boodschappen' and household_id is null), array['spar'], true),
(null, 'picnic', 'Picnic', (select id from categories where key = 'boodschappen' and household_id is null), array['picnic'], true),
(null, 'ekoplaza', 'Ekoplaza', (select id from categories where key = 'boodschappen' and household_id is null), array['ekoplaza'], true),
(null, 'vomar', 'Vomar', (select id from categories where key = 'boodschappen' and household_id is null), array['vomar'], true),
(null, 'hoogvliet', 'Hoogvliet', (select id from categories where key = 'boodschappen' and household_id is null), array['hoogvliet'], true),
(null, 'nettorama', 'Nettorama', (select id from categories where key = 'boodschappen' and household_id is null), array['nettorama'], true),
(null, 'poiesz', 'Poiesz', (select id from categories where key = 'boodschappen' and household_id is null), array['poiesz'], true),
-- Drogist/verzorging
(null, 'etos', 'Etos', (select id from categories where key = 'persoonlijke_verzorging' and household_id is null), array['etos'], true),
(null, 'kruidvat', 'Kruidvat', (select id from categories where key = 'persoonlijke_verzorging' and household_id is null), array['kruidvat'], true),
(null, 'trekpleister', 'Trekpleister', (select id from categories where key = 'persoonlijke_verzorging' and household_id is null), array['trekpleister'], true),
(null, 'douglas', 'Douglas', (select id from categories where key = 'persoonlijke_verzorging' and household_id is null), array['douglas'], true),
(null, 'ici_paris', 'ICI Paris', (select id from categories where key = 'persoonlijke_verzorging' and household_id is null), array['ici paris'], true),
-- Huis & tuin
(null, 'action', 'Action', (select id from categories where key = 'overig' and household_id is null), array['action'], true),
(null, 'hema', 'HEMA', (select id from categories where key = 'overig' and household_id is null), array['hema'], true),
(null, 'blokker', 'Blokker', (select id from categories where key = 'overig' and household_id is null), array['blokker'], true),
(null, 'praxis', 'Praxis', (select id from categories where key = 'inventaris_onderhoud' and household_id is null), array['praxis'], true),
(null, 'gamma', 'Gamma', (select id from categories where key = 'inventaris_onderhoud' and household_id is null), array['gamma'], true),
(null, 'karwei', 'Karwei', (select id from categories where key = 'inventaris_onderhoud' and household_id is null), array['karwei'], true),
(null, 'hornbach', 'Hornbach', (select id from categories where key = 'inventaris_onderhoud' and household_id is null), array['hornbach'], true),
(null, 'ikea', 'IKEA', (select id from categories where key = 'inventaris_onderhoud' and household_id is null), array['ikea'], true),
(null, 'xenos', 'Xenos', (select id from categories where key = 'overig' and household_id is null), array['xenos'], true),
-- Vervoer
(null, 'ns', 'NS', (select id from categories where key = 'openbaar_vervoer' and household_id is null), array['ns groep', 'ns internationaal'], true),
(null, 'ov_chipkaart', 'OV-chipkaart', (select id from categories where key = 'openbaar_vervoer' and household_id is null), array['ov-chipkaart', 'ov chipkaart'], true),
(null, 'ovpay', 'OVpay', (select id from categories where key = 'openbaar_vervoer' and household_id is null), array['ovpay'], true),
(null, 'gvb', 'GVB', (select id from categories where key = 'openbaar_vervoer' and household_id is null), array['gvb'], true),
(null, 'ret', 'RET', (select id from categories where key = 'openbaar_vervoer' and household_id is null), array['ret'], true),
(null, 'htm', 'HTM', (select id from categories where key = 'openbaar_vervoer' and household_id is null), array['htm'], true),
(null, 'arriva', 'Arriva', (select id from categories where key = 'openbaar_vervoer' and household_id is null), array['arriva'], true),
(null, 'connexxion', 'Connexxion', (select id from categories where key = 'openbaar_vervoer' and household_id is null), array['connexxion'], true),
(null, 'q_park', 'Q-Park', (select id from categories where key = 'vervoer_brandstof' and household_id is null), array['q-park', 'qpark'], true),
(null, 'shell', 'Shell', (select id from categories where key = 'vervoer_brandstof' and household_id is null), array['shell'], true),
(null, 'bp', 'BP', (select id from categories where key = 'vervoer_brandstof' and household_id is null), array['bp,', 'bp tankstation'], true),
(null, 'esso', 'Esso', (select id from categories where key = 'vervoer_brandstof' and household_id is null), array['esso'], true),
(null, 'tango', 'Tango', (select id from categories where key = 'vervoer_brandstof' and household_id is null), array['tango'], true),
(null, 'fastned', 'Fastned', (select id from categories where key = 'vervoer_brandstof' and household_id is null), array['fastned'], true),
(null, 'greenwheels', 'Greenwheels', (select id from categories where key = 'vervoer_brandstof' and household_id is null), array['greenwheels'], true),
(null, 'swapfiets', 'Swapfiets', (select id from categories where key = 'abonnementen' and household_id is null), array['swapfiets'], true),
(null, 'felyx', 'Felyx', (select id from categories where key = 'vervoer_brandstof' and household_id is null), array['felyx'], true),
(null, 'check_mobility', 'Check', (select id from categories where key = 'vervoer_brandstof' and household_id is null), array['check mobility'], true),
-- Telecom/energie
(null, 'kpn', 'KPN', (select id from categories where key = 'internet_tv' and household_id is null), array['kpn'], true),
(null, 'odido', 'Odido', (select id from categories where key = 'mobiel' and household_id is null), array['odido'], true),
(null, 'vodafone', 'Vodafone', (select id from categories where key = 'mobiel' and household_id is null), array['vodafone'], true),
(null, 'ziggo', 'Ziggo', (select id from categories where key = 'internet_tv' and household_id is null), array['ziggo'], true),
(null, 'simyo', 'Simyo', (select id from categories where key = 'mobiel' and household_id is null), array['simyo'], true),
(null, 'eneco', 'Eneco', (select id from categories where key = 'energie' and household_id is null), array['eneco'], true),
(null, 'vattenfall', 'Vattenfall', (select id from categories where key = 'energie' and household_id is null), array['vattenfall'], true),
(null, 'essent', 'Essent', (select id from categories where key = 'energie' and household_id is null), array['essent'], true),
(null, 'greenchoice', 'Greenchoice', (select id from categories where key = 'energie' and household_id is null), array['greenchoice'], true),
(null, 'budget_energie', 'Budget Energie', (select id from categories where key = 'energie' and household_id is null), array['budget energie'], true),
(null, 'vandebron', 'Vandebron', (select id from categories where key = 'energie' and household_id is null), array['vandebron'], true),
(null, 'waternet', 'Waternet', (select id from categories where key = 'water' and household_id is null), array['waternet'], true),
(null, 'vitens', 'Vitens', (select id from categories where key = 'water' and household_id is null), array['vitens'], true),
(null, 'evides', 'Evides', (select id from categories where key = 'water' and household_id is null), array['evides'], true),
-- Verzekering/zorg
(null, 'zilveren_kruis', 'Zilveren Kruis', (select id from categories where key = 'zorgverzekering' and household_id is null), array['zilveren kruis'], true),
(null, 'vgz', 'VGZ', (select id from categories where key = 'zorgverzekering' and household_id is null), array['vgz'], true),
(null, 'cz', 'CZ', (select id from categories where key = 'zorgverzekering' and household_id is null), array['cz zorgverzekeraar', 'cz,'], true),
(null, 'menzis', 'Menzis', (select id from categories where key = 'zorgverzekering' and household_id is null), array['menzis'], true),
(null, 'dsw', 'DSW', (select id from categories where key = 'zorgverzekering' and household_id is null), array['dsw'], true),
(null, 'onvz', 'ONVZ', (select id from categories where key = 'zorgverzekering' and household_id is null), array['onvz'], true),
(null, 'unive', 'Univé', (select id from categories where key = 'zorgverzekering' and household_id is null), array['unive', 'univé'], true),
(null, 'centraal_beheer', 'Centraal Beheer', (select id from categories where key = 'overige_verzekeringen' and household_id is null), array['centraal beheer'], true),
(null, 'interpolis', 'Interpolis', (select id from categories where key = 'overige_verzekeringen' and household_id is null), array['interpolis'], true),
(null, 'fbto', 'FBTO', (select id from categories where key = 'overige_verzekeringen' and household_id is null), array['fbto'], true),
(null, 'ohra', 'Ohra', (select id from categories where key = 'overige_verzekeringen' and household_id is null), array['ohra'], true),
(null, 'nationale_nederlanden', 'Nationale-Nederlanden', (select id from categories where key = 'overige_verzekeringen' and household_id is null), array['nationale-nederlanden', 'nationale nederlanden'], true),
-- Overheid
(null, 'belastingdienst', 'Belastingdienst', (select id from categories where key = 'teruggave_belasting' and household_id is null), array['belastingdienst'], true),
(null, 'belastingdienst_toeslagen', 'Belastingdienst Toeslagen', (select id from categories where key = 'toeslagen' and household_id is null), array['belastingdienst/toeslagen', 'belastingdienst toeslagen'], true),
(null, 'svb', 'SVB', (select id from categories where key = 'kinderbijslag' and household_id is null), array['svb'], true),
(null, 'uwv', 'UWV', (select id from categories where key = 'uitkering' and household_id is null), array['uwv'], true),
(null, 'duo', 'DUO', (select id from categories where key = 'aflossingen' and household_id is null), array['duo,', 'dienst uitvoering onderwijs'], true),
(null, 'cjib', 'CJIB', (select id from categories where key = 'overig' and household_id is null), array['cjib'], true),
(null, 'rdw', 'RDW', (select id from categories where key = 'auto_onderhoud_apk' and household_id is null), array['rdw'], true),
(null, 'gemeente', 'Gemeente', (select id from categories where key = 'gemeentebelasting' and household_id is null), array['gemeente '], true),
(null, 'waterschap', 'Waterschap', (select id from categories where key = 'waterschapsbelasting' and household_id is null), array['waterschap'], true),
-- Bezorging/eten
(null, 'thuisbezorgd', 'Thuisbezorgd', (select id from categories where key = 'uit_eten_bezorgen' and household_id is null), array['thuisbezorgd'], true),
(null, 'uber_eats', 'Uber Eats', (select id from categories where key = 'uit_eten_bezorgen' and household_id is null), array['uber eats'], true),
(null, 'dominos', 'Domino''s', (select id from categories where key = 'uit_eten_bezorgen' and household_id is null), array['domino''s', 'dominos pizza'], true),
(null, 'new_york_pizza', 'New York Pizza', (select id from categories where key = 'uit_eten_bezorgen' and household_id is null), array['new york pizza'], true),
(null, 'flink', 'Flink', (select id from categories where key = 'uit_eten_bezorgen' and household_id is null), array['flink'], true),
(null, 'gorillas', 'Gorillas', (select id from categories where key = 'uit_eten_bezorgen' and household_id is null), array['gorillas'], true),
(null, 'crisp', 'Crisp', (select id from categories where key = 'uit_eten_bezorgen' and household_id is null), array['crisp'], true),
-- Abonnementen
(null, 'netflix', 'Netflix', (select id from categories where key = 'abonnementen' and household_id is null), array['netflix'], true),
(null, 'spotify', 'Spotify', (select id from categories where key = 'abonnementen' and household_id is null), array['spotify'], true),
(null, 'videoland', 'Videoland', (select id from categories where key = 'abonnementen' and household_id is null), array['videoland'], true),
(null, 'disney_plus', 'Disney+', (select id from categories where key = 'abonnementen' and household_id is null), array['disney+', 'disney plus'], true),
(null, 'hbo_max', 'HBO Max', (select id from categories where key = 'abonnementen' and household_id is null), array['hbo max'], true),
(null, 'ziggo_sport', 'Ziggo Sport', (select id from categories where key = 'abonnementen' and household_id is null), array['ziggo sport'], true),
(null, 'npo_plus', 'NPO Plus', (select id from categories where key = 'abonnementen' and household_id is null), array['npo plus'], true),
(null, 'basic_fit', 'Basic-Fit', (select id from categories where key = 'sport' and household_id is null), array['basic-fit', 'basic fit'], true),
(null, 'sportcity', 'SportCity', (select id from categories where key = 'sport' and household_id is null), array['sportcity'], true),
(null, 'fit_for_free', 'Fit For Free', (select id from categories where key = 'sport' and household_id is null), array['fit for free'], true),
(null, 'strava', 'Strava', (select id from categories where key = 'sport' and household_id is null), array['strava'], true),
(null, 'icloud', 'iCloud', (select id from categories where key = 'abonnementen' and household_id is null), array['icloud', 'apple.com/bill'], true),
(null, 'google_one', 'Google One', (select id from categories where key = 'abonnementen' and household_id is null), array['google one', 'google *one'], true),
-- Retail/online
(null, 'bol', 'bol', (select id from categories where key = 'overig' and household_id is null), array['bol.com', 'bol,'], true),
(null, 'coolblue', 'Coolblue', (select id from categories where key = 'overig' and household_id is null), array['coolblue'], true),
(null, 'amazon_nl', 'Amazon.nl', (select id from categories where key = 'overig' and household_id is null), array['amazon.nl', 'amazon nl'], true),
(null, 'wehkamp', 'Wehkamp', (select id from categories where key = 'overig' and household_id is null), array['wehkamp'], true),
(null, 'zalando', 'Zalando', (select id from categories where key = 'kleding' and household_id is null), array['zalando'], true),
(null, 'decathlon', 'Decathlon', (select id from categories where key = 'sport' and household_id is null), array['decathlon'], true),
(null, 'mediamarkt', 'MediaMarkt', (select id from categories where key = 'overig' and household_id is null), array['mediamarkt'], true),
(null, 'marktplaats', 'Marktplaats', (select id from categories where key = 'overig' and household_id is null), array['marktplaats'], true),
(null, 'vinted', 'Vinted', (select id from categories where key = 'kleding' and household_id is null), array['vinted'], true),
-- Fintech/P2P — payment rails, not merchants: no default category (docs/09
-- §1 stage 6 resolves the underlying merchant from the free-text remainder).
(null, 'tikkie', 'Tikkie', null, array['tikkie'], true),
(null, 'wero', 'Wero', null, array['wero'], true),
(null, 'ideal', 'iDEAL', null, array['ideal'], true),
(null, 'paypal', 'PayPal', null, array['paypal'], true),
(null, 'klarna', 'Klarna', null, array['klarna'], true),
(null, 'in3', 'in3', null, array['in3'], true),
(null, 'riverty', 'Riverty', null, array['riverty'], true),
(null, 'afterpay', 'AfterPay', null, array['afterpay'], true),
(null, 'billink', 'Billink', null, array['billink'], true)
on conflict (key) where household_id is null do nothing;
